Feat/challenge 03 loops conditionals
JosepRubio/JavaScript-foundations-challenge-1 pull request #3
Opened 2023-10-31 19:30 UTC by JosepRubio

2023-11-05 19:01 UTC, tictools requested changes

2023-11-05 19:01 UTC, tictools commented on challenge_03_loops-conditionals/README.md
⚠️ FIX: move file at project root level

2023-11-05 19:01 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_00.js
> +if (animal == "cat") {
⚠️ FIX: Change animal to different values to make sure it works in all cases

2023-11-05 19:01 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_01.js
> +let number = 5;
⚠️ FIX: Change the variable to test it works for different cases. Print result.

2023-11-05 19:01 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +for (let i = 10; i < 40; i++) {
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

2023-11-05 19:01 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +for (let j = 10; j < 40; j++) {
You should take in account what `j` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

2023-11-05 19:01 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_02.js
> +for (let i = 1; i <= 100; i++) {
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable


This is the output of your script
```
Checkpoint!10
Checkpoint!20
Checkpoint!30
Checkpoint!40
Half way there!50
Checkpoint!60
Checkpoint!70
Checkpoint!80
Checkpoint!90
You made it!100
All, done!
```

have you tested it before pushing? 🤔

⚠️ FIX: needs work.

2023-11-05 19:01 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_01.js
> +/*let number = 10;
⚠️ FIX: remove commented code

2023-11-05 19:01 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_01.js
> +  else if (number % 2 === 1) console.log("odd: ", number);
```suggestion
  else if (number % 2 !== 0) console.log("odd: ", number);
```

2023-11-05 19:01 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_02.js
> +while (number <= 100) {
This is the output of your script
```
Checkpoint!10
Checkpoint!20
Checkpoint!30
Checkpoint!40
Half way there!50
Checkpoint!60
Checkpoint!70
Checkpoint!80
Checkpoint!90
You made it!100
All, done!
```

have you tested it before pushing? 🤔

⚠️ FIX: needs work.

2023-11-11 19:43 UTC, tictools approved these changes

2023-11-11 20:58 UTC, UnPiquito approved these changes

2023-11-13 17:49 UTC, merged